// <auto-generated />
namespace easyfis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class easyfisv2db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(easyfisv2db));
        
        string IMigrationMetadata.Id
        {
            get { return "201603221919393_easyfisv2db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
